/** NativeWind classes for Home screen (index.tsx) */

export const home = {
  container: 'flex-1 bg-background',
  loadingContainer: 'flex-1 items-center justify-center bg-background',
  safeArea: 'flex-1 px-5',
  header: 'my-6 flex-row items-center justify-between',
  welcomeText: 'font-heading text-[22px] font-bold text-foreground',
  cityBadge: 'mt-1 flex-row items-center gap-1',
  cityText: 'font-body text-sm text-primary',
  logoutBtn: 'rounded-lg border border-destructive/40 px-3 py-1.5',
  searchSection:
    'mb-6 h-12 flex-row items-center rounded-xl border border-border bg-card px-4',
  searchIcon: 'mr-2.5',
  searchInput: 'flex-1 font-body text-sm text-foreground',
  sectionTitle: 'mb-4 font-heading text-lg font-bold text-foreground',
  emptyState: 'flex-1 items-center justify-center py-16',
  shopCard: 'overflow-hidden rounded-2xl border border-border bg-card',
  shopBanner: 'h-[120px] w-full bg-muted',
  shopCardDetails: 'p-4',
  shopCardHeader: 'flex-row items-center justify-between',
  shopName: 'font-body text-base font-bold text-foreground',
  ratingBadge: 'flex-row items-center rounded bg-secondary px-2 py-0.5',
  modalOverlay: 'flex-1 justify-end bg-black/85',
  modalContent: 'max-h-[90%] rounded-t-3xl border border-border bg-card',
  closeModalBtn: 'mr-2 self-end p-4',
  modalBanner: 'h-[180px] w-full bg-muted',
  modalBody: 'p-6',
  divider: 'my-5 h-px bg-border',
  workerRow: 'mb-3 flex-row items-center gap-4 rounded-xl border border-border/50 bg-secondary/40 p-3',
  workerAvatar: 'h-12 w-12 rounded-full bg-muted',
  tagContainer: 'mt-1.5 flex-row flex-wrap gap-1.5',
  specialtyTag: 'rounded border border-primary/20 bg-primary/10 px-2 py-0.5',
  addBtn: 'flex-row items-center justify-center gap-2 rounded-xl bg-primary py-3',
  addBtnSecondary: 'mt-2 flex-row items-center justify-center gap-2 rounded-xl border border-border bg-secondary py-3',
  addBtnText: 'font-body font-bold text-primary-foreground',
  addBtnTextSecondary: 'font-body font-bold text-primary',
  barberShopCard:
    'rounded-2xl border border-border bg-card p-4 mb-0',
  modalInput:
    'h-12 rounded-xl border border-input bg-card px-4 font-body text-sm text-foreground',
  citySelectBtn:
    'h-10 flex-1 items-center justify-center rounded-lg border border-border',
  citySelectActive: 'border-primary bg-primary/10',
  submitBtn: 'mt-2.5 h-12 items-center justify-center rounded-xl bg-primary',
  actionRow: 'mb-6 flex-row gap-3',
  actionCard: 'min-h-[140px] flex-1 rounded-2xl border border-border bg-card p-4',
  actionCardPrimary: 'border-primary/30',
  actionCardSecondary: 'border-border',
  actionIconWellPrimary:
    'h-11 w-11 items-center justify-center rounded-xl bg-primary/10',
  actionIconWellSecondary:
    'h-11 w-11 items-center justify-center rounded-xl bg-secondary',
  accountChip: 'rounded-lg border border-border bg-card px-3 py-1.5',
  listHeader: 'gap-0 pb-2',
  searchResultBadge: 'mb-3 flex-row items-center justify-between',
  resultCount: 'font-body text-sm text-muted-foreground',
  mapToggle: 'flex-row items-center justify-between mb-2',
  mapToggleLabel: 'font-body text-sm font-semibold text-foreground',
  mapToggleChevron: 'p-1',
  mapCollapsed: 'h-0 overflow-hidden',
  clearSearchBtn: 'p-2 -mr-2',
  shopDistance: 'font-body text-xs text-primary mt-1',
} as const;
